# Lesson 1. Introduction to Writing Functions

After completing this chapter, you will be able to:

- Explain how using functions help you to write DRY (Don’t Repeat Yourself) code in Python.
- Describe the components needed to define a function in Python.
- Write and execute a custom function in Python.
- Write nested functions (functions inside of other functions) in Python

A function is a reusable block of code that performs a specific task. Functions receive inputs to which code is applied and return outputs (or results) of the code.

#### input parameter –> function does something –> output results

For example:

In [2]:
x = 5

# Print value of input
print(x)

5


## The Benefits of Functions
- Modularity: Functions only need to be defined once in a workflow (e.g. Jupyter Notebook file, script). Functions that you write for specific tasks can be used over and over, without needing to redefine the function again. A function that you write for one Python workflow can also be reused in other workflows!

- Fewer variables: When you run a function, the intermediate variables (i.e. placeholders) that it creates are not stored as explicit variables unless you specify otherwise. This saves memory and keeps your Python environment cleaner.

- Better documentation: Well-documented functions help other users understand the steps of your processing and helps your future self to understand previously written code.

- Easier to maintain and edit your code: Because a function is only defined once in the workflow, you can simply just update the original function definition. Then, each instance in which you call that function in your code (i.e. when same task is performed) is automatically updated.

- Testing: You won’t learn about this in this class, but writing functions allows you to more easily test your code to identify issues (i.e. bugs).

### Write Modular Functions and Code
A well-defined function only does one thing, but it does it well and often in a variety of contexts. Often, the operations contained in a good function are generally useful for many tasks.

Take, for instance, the numpy function called mean(), which computes mean values from a numpy array.

This function only does one thing (i.e. computes a mean); however, you may use the np.mean() function many times in your code on multiple numpy arrays because it has been defined to take any numpy array as an input.

Well-written functions help you document your workflow because:

- They are well-documented by clearly outlining the inputs and outputs.
- They use descriptive names that help you better understand the task that the function performs.

It is a good idea to learn how to:

- Modularize your code into generalizable tasks using functions.
- Write functions for parts of your code which include repeated steps.
- Document your functions clearly, specifying the structure of the inputs and outputs with clear comments about what the function can do.

# Lesson 2. Write Functions

There are several components needed to define a function in Python, including the def keyword, function name, parameters (inputs), and the return statement, which specifies the output of the function.

In [4]:
# def function_name(parameter):
#    some code here    
#    return output

Note that functions in Python can be defined with multiple input parameters as needed:

#### def function_name(arr_1, arr_2):

### Return Statement
In Python, function definitions need a return statement to specify the output that will be returned by the function.

The return statement can return one or more values or objects and can follow multiple lines of code as needed to complete the task (i.e. code to create the output that will be returned by the function).

###  Docstring
In Python, functions should also contain a docstring, or a multi-line documentation comment, that provides details about the function, including the specifics of the input parameters and the returns (e.g. type of objects, additional description) and any other important documentation about how to use the function. 

In [5]:
def function_name(data):
    """Docstrings should include a description of the function here 
    as well as identify the parameters (inputs) that the function 
    can take and the return (output) provided by the function,
    as shown below. 
    
    Parameters
    ----------
    input : type
        Description of input.
    
    Returns
    ------
    output : type
        Description of output.
    """
   # some code here
    
    return output

## Write a Function in Python

In [8]:
def mm_to_in(mm):
    """Convert input from millimeters to inches. 
    
    Parameters
    ----------
    mm : int or float
        Numeric value with units in millimeters.

    Returns
    ------
    inches : int or float
        Numeric value with units in inches.
    """
    inches = mm / 25.4    
    return inches

## Call Custom Functions in Python
Now that you have defined the function mm_to_in(), you can call it as needed to convert units.

In [9]:
# Average monthly precip (mm) in Jan for Boulder, CO
precip_jan_mm = 17.78

# Convert to inches
mm_to_in(mm = precip_jan_mm)

0.7000000000000001

In [10]:
# You can create a new variable to store the output of the function as follows

In [11]:
# Create new variable with converted values
precip_jan_in = mm_to_in(mm = precip_jan_mm)

precip_jan_in

0.7000000000000001

### Applying the Same Function to Multiple Object Types
Since you know that numeric values can also be stored in numpy arrays, you can also provide a numpy array as an input to the function.

In [12]:
# Import necessary packages
import numpy as np

In [13]:
# Average monthly precip (mm) for Boulder, CO
avg_monthly_precip_mm = np.array([17.78, 19.05, 46.99, 74.422, 
                                  77.47, 51.308, 49.022, 41.148, 
                                  46.736, 33.274, 35.306, 21.336])

# Convert to inches
mm_to_in(mm = avg_monthly_precip_mm)

array([0.7 , 0.75, 1.85, 2.93, 3.05, 2.02, 1.93, 1.62, 1.84, 1.31, 1.39,
       0.84])

Similarly, you know that numeric values can be stored in a column in a **pandas dataframe**, so you can also provide a column in a pandas dataframe as an input to the function and store the results of the function in a new column.

In [14]:
# Import necessary packages
import pandas as pd

In [15]:
# Average monthly precip (mm) in 2002 for Boulder, CO
precip_2002 = pd.DataFrame(columns=["month", "precip_mm"],
                           data=[
                                ["Jan", 27.178],  ["Feb", 11.176],
                                ["Mar", 38.100],  ["Apr", 5.080],
                                ["May", 81.280],  ["June", 29.972],
                                ["July", 2.286],  ["Aug", 36.576],
                                ["Sept", 38.608], ["Oct", 61.976],
                                ["Nov", 19.812],  ["Dec", 0.508]
                           ])

In [16]:
# Create new column with precip in inches
precip_2002["precip_in"] = mm_to_in(mm = precip_2002["precip_mm"])

precip_2002

month  precip_mm  precip_in
0    Jan     27.178       1.07
1    Feb     11.176       0.44
2    Mar     38.100       1.50
3    Apr      5.080       0.20
4    May     81.280       3.20
5   June     29.972       1.18
6   July      2.286       0.09
7    Aug     36.576       1.44
8   Sept     38.608       1.52
9    Oct     61.976       2.44
10   Nov     19.812       0.78
11   Dec      0.508       0.02

Since you know that numeric calculations cannot be performed directly on a list, you know that this function will not execute successfully if provided a list as an input.

This is an important idea to keep in mind as you write functions in Python.

# Call Help on a Custom Function
Just like you can call help() on a function provided by a Python package such as numpy (e.g. help(np.mean), you can also call help() on custom functions.

In [18]:
# Call help on custom function
help(mm_to_in)

Help on function mm_to_in in module __main__:

mm_to_in(mm)
    Convert input from millimeters to inches. 
    
    Parameters
    ----------
    mm : int or float
        Numeric value with units in millimeters.
    
    Returns
    ------
    inches : int or float
        Numeric value with units in inches.



## Combine Multiple Function Calls on a Single Object in Python
Imagine that you want to convert the units of a numpy array using the function mm_to_in() and then calculate a mean using np.mean().

In [19]:
# Convert to inches and calculate mean
avg_monthly_precip_mean_in = np.mean(mm_to_in(mm = avg_monthly_precip_mm))

avg_monthly_precip_mean_in

1.6858333333333333

# Lesson 3. Write Functions with Multiple Parameters in Python

Learning Objectives
- Write and execute custom functions with multiple input parameters in Python.
- Write and execute custom functions with optional input parameters in Python.

You can write functions that take in more than one parameter by defining as many parameters as needed, for example:



In [20]:
def multiply_values(x,y):
    z = x * y
    return z

In [21]:
# Call function with numeric values
multiply_values(x = 0.7, y = 25.4)

17.779999999999998

In [23]:
# Average monthly precip (inches) for Jan in Boulder, CO
precip_jan_in = 0.7

# Conversion factor from inches to millimeters
to_mm = 25.4

In [24]:
# Call function with pre-defined variables
precip_jan_mm = multiply_values(
    x = precip_jan_in, 
    y = to_mm)

precip_jan_mm

17.779999999999998

## Combine Unit Conversion and Calculation of Statistics into One Function

Now imagine that you want to both convert the units of a numpy array from millimeters to inches and calculate the mean value along a specified axis for either columns or rows.

Begin by defining the function with a descriptive name and the two necessary parameters:

- the input array with values in millimeters
- the axis value for the mean calculation

In [25]:
def mean_mm_to_in_arr(arr_mm, axis_value):
    mean_arr_mm = np.mean(arr_mm, axis = axis_value) # a mean along a specified axis.
    mean_arr_in = mean_arr_mm / 25.4 
        
    return mean_arr_in

In [26]:
# Import necessary package to run function
import numpy as np

In [27]:
# 2d array of average monthly precip (mm) for 2002 and 2013 in Boulder, CO
precip_2002_2013_mm = np.array([[27.178, 11.176, 38.1, 5.08, 81.28, 29.972, 
                                 2.286, 36.576, 38.608, 61.976, 19.812, 0.508],
                                [6.858, 28.702, 43.688, 105.156, 67.564, 15.494,  
                                 26.162, 35.56 , 461.264, 56.896, 7.366, 12.7]
                               ])

In [29]:
# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm, 
                                    axis_value = 0) # rows

monthly_mean_in

array([0.67 , 0.785, 1.61 , 2.17 , 2.93 , 0.895, 0.56 , 1.42 , 9.84 ,
       2.34 , 0.535, 0.26 ])

In [30]:
# Calculate yearly mean (inches) for precip_2002_2013
yearly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm, 
                                   axis_value = 1) # col

yearly_mean_in

array([1.15666667, 2.84583333])

## Define Optional Input Parameters for a Function

In [31]:
def mean_mm_to_in_arr(arr_mm, axis_value=None):
    """Calculate mean values of input array and convert values 
    from millimeters to inches. If an axis is specified,
    the mean will be calculated along that axis. 

    
    Parameters
    ----------
    arr_mm : numpy array
        Numeric values in millimeters.
    axis_value : int (optional)
        0 to calculate mean for each column.
        1 to calculate mean for each row.

    Returns
    ------
    mean_arr_in : numpy array
        Mean values of input array in inches.
    """   
    if axis_value is None:
        mean_arr_mm = np.mean(arr_mm)        
    else:
        mean_arr_mm = np.mean(arr_mm, axis = axis_value)
    
    mean_arr_in = mean_arr_mm / 25.4 
        
    return mean_arr_in

In [32]:
# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_2013_mm, 
                                    axis_value = 0)

monthly_mean_in

array([0.67 , 0.785, 1.61 , 2.17 , 2.93 , 0.895, 0.56 , 1.42 , 9.84 ,
       2.34 , 0.535, 0.26 ])

However, now you can also provide a one-dimensional array as an input without a specified axis and receive the appropriate output.

In [35]:
precip_2002_mm =  arr_mm = precip_2002_2013_mm[0]

In [36]:
# Calculate mean (inches) for precip_2002
monthly_mean_in = mean_mm_to_in_arr(arr_mm = precip_2002_mm)

monthly_mean_in

1.1566666666666667

## Combine Download and Import of Data Files into One Function
You can also write multi-parameter functions to combine other tasks into one function, such as downloading and importing data files into a pandas dataframe.

Think about the code that you need to include in the function:

- download data file from URL: et.data.get_data(url=file_url)
- import data file into pandas dataframe: pd.read_csv(path)

From this code, you can see that you will need two input parameters for the combined function:

- the URL to the data file
- the path to the downloaded file
Begin by specifying a function name and the placeholder variable names for the necessary input parameters.

In [37]:
def download_import_df(file_url, path):    
    
    et.data.get_data(url=file_url)      
    os.chdir(os.path.join(et.io.HOME, "earth-analytics"))    
    df = pd.read_csv(path)
    
    return df

Documentació:

In [39]:
def download_import_df(file_url, path):   
    """Download file from specified URL and import file
    into a pandas dataframe from a specified path. 
    
    Working directory is set to earth-analytics directory 
    under home, which is automatically created by the
    download. 

    
    Parameters
    ----------
    file_url : str
        URL to CSV file (http or https).
    path : str
        Path to CSV file using relative path
        to earth-analytics directory under home.        

    Returns
    ------
    df : pandas dataframe
        Dataframe imported from downloaded CSV file.
    """ 
    
    et.data.get_data(url=file_url)      
    os.chdir(os.path.join(et.io.HOME, "earth-analytics"))    
    df = pd.read_csv(path)
    
    return df

In [40]:
# Import necessary packages to run function
import os
import pandas as pd
import earthpy as et

In [41]:
# URL for average monthly precip (inches) for 2002 and 2013 in Boulder, CO
precip_2002_2013_df_url = "https://ndownloader.figshare.com/files/12710621"

# Path to downloaded .csv file with headers
precip_2002_2013_df_path = os.path.join("data", "earthpy-downloads", 
                                        "precip-2002-2013-months-seasons.csv")

Using these variables, you can now call the function to download and import the file into a pandas dataframe.

In [42]:
# Create dataframe using download/import function
precip_2002_2013_df = download_import_df(
    file_url = precip_2002_2013_df_url, 
    path = precip_2002_2013_df_path)

precip_2002_2013_df

months  precip_2002  precip_2013 seasons
0     Jan         1.07         0.27  Winter
1     Feb         0.44         1.13  Winter
2     Mar         1.50         1.72  Spring
3     Apr         0.20         4.14  Spring
4     May         3.20         2.66  Spring
5    June         1.18         0.61  Summer
6    July         0.09         1.03  Summer
7     Aug         1.44         1.40  Summer
8    Sept         1.52        18.16    Fall
9     Oct         2.44         2.24    Fall
10    Nov         0.78         0.29    Fall
11    Dec         0.02         0.50  Winter

# Exercici: Practice Writing Multi-Parameter Functions for Pandas Dataframes

You have a function that combines the mean calculation along a specified axis and the conversion from millimeters to inches for a numpy array.

How might you need to change this function to create a similar function for pandas dataframe, but now converting from inches to millimeters?

For the mean, you can run summary statistics on pandas using a specified axis (just like a numpy array) with the following code:

df.mean(axis = axis_value) 
With the axis value 0, the code will calculate a mean for each numeric column in the dataframe.

With the axis value 1, the code will calculate a mean for each row with numeric values in the dataframe.

Think about which code lines in the existing function mean_mm_to_in_arr() can be modified to run the equivalent code on a pandas dataframe.

Note that the df.mean(axis = axis_value) returns the mean values of a dataframe (along the specified axis) as a pandas series.

In [52]:
def mean_inch_to_mm_arr(arr_inch, axis_value):
    mean_arr_inch = arr_inch.mean(axis = axis_value) # a mean along a specified axis.
    mean_arr_mm = 25.4 * mean_arr_inch 
        
    return mean_arr_mm

In [54]:
# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_inch_to_mm_arr(arr_inch = precip_2002_2013_df, 
                                    axis_value = 1)

monthly_mean_in

0      17.018
1      19.939
2      40.894
3      55.118
4      74.422
5      22.733
6      14.224
7      36.068
8     249.936
9      59.436
10     13.589
11      6.604
dtype: float64

In [55]:
# Calculate monthly mean (inches) for precip_2002_2013
monthly_mean_in = mean_inch_to_mm_arr(arr_inch = precip_2002_2013_df, 
                                    axis_value = 0)

monthly_mean_in

precip_2002    29.379333
precip_2013    72.284167
dtype: float64